[tool.ruff]
line-length = 100
target-version = "py312"
select = [
  "E", "F",  # pycodestyle + pyflakes
  "I",       # isort
  "UP",      # pyupgrade
  "B",       # bugbear
]
ignore = [
  "E501",    # line length
  "F401",
  "F403",
]

[tool.ruff.lint.isort]
known-first-party = ["app", "config"]
combine-as-imports = true
