[tool.ruff]
line-length = 100
target-version = "py312"

per-file-ignores = {
  "**/config/settings/dev.py" = ["F403", "F405"],
  "**/config/settings/prod.py" = ["F403", "F405"],
}

[tool.ruff.lint]
select = [
  "E", "F",  # pycodestyle + pyflakes
  "I",       # isort
  "UP",      # pyupgrade
  "B",       # bugbear
]

ignore = [
  "E402",
  "E501",    # line length
]

[tool.ruff.lint.isort]
known-first-party = ["app", "config"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"**/config/settings/*.py" = ["F401", "F403", "F405"]
"tests/conftest.py" = ["E402"]
