name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint (ruff)
        run: |
          python -m ruff --version
          python -m ruff check .

      - name: Run tests (pytest from app dir)
        working-directory: app
        run: |
          python -m pytest ../tests -q

  openai_smoke:
    runs-on: ubuntu-latest
    needs: lint_and_test
    env:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # safe: env can read secrets
      EFB_LLM_CALL_BUDGET: "12"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - name: No key? Skip this job politely
        if: ${{ env.OPENAI_API_KEY == '' }}
        run: echo "OPENAI_API_KEY not set; skipping OpenAI smoke run."

      - name: Checkout
        if: ${{ env.OPENAI_API_KEY != '' }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ env.OPENAI_API_KEY != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Migrate (SQLite)
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: python app/manage.py migrate --noinput

      - name: Smoke run (3 conversations, real OpenAI)
        if: ${{ env.OPENAI_API_KEY != '' }}
        run: python app/manage.py simulate_foods --runs=3
